#' Generic print function for metadiag object in bamdit
#' @param x The object generated by the function metadiag.
#'
#' @param digits The number of significant digits printed. The default value is 3.
#'
#' @param ... \dots
#'
#' @export

print.metadiag <- function(x, digits = 3,...)
{
  print(x$BUGSoutput)

}
